name: test_iot
description: AWS IoT Flutter Test
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaml: ^3.1.3
  provider: ^6.0.0
  amazon_cognito_identity_dart_2: ^3.8.1
  mqtt5_client: ^4.11.0
  crypto: ^3.0.6
  intl: ^0.20.0
  aws_signature_v4: ^0.6.4
  aws_common: ^0.7.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

